# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent
LABEL io.k8s.description="Apache http builder image,on build" \
      io.k8s.display-name="APache HttpServer" \
      io.openshift.expose-services="8080:httpd" \
      io.openshift.tags="apache,httpd"

EXPOSE 8080
RUN sed -i "s/Listen 80/Listen 8080/g" /etc/httpd/conf/httpd.conf && \
    chgrp -R 0 /var/log/httpd /var/run/httpd && \
    chmod -R g=u /var/log/httpd /var/run/httpd

USER 1001

