# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent
# Change port to 8080
EXPOSE 8080
# Lables are consumed by openshift
LABEL io.k8s.description="base Apache Http Server child image, Use OnBuild" \
      io.k8s.display-name="Apache Http Server" \
      io.openshift.expose-services="8080:httpd" \
      io.openshift.tags="Apache, httpd"
# change webserver port to 8080
RUN sed -i "s/Lsten 80/Listen 8080/g" /etc/httpd/conf/httpd.conf

# Permissions to allow container to run openshift
RUN chgrp -R 0 /var/log/httpd /var/run/httpd && \
    chmod -R g=u /var/log/httpd /var/run/httpd

# Non Previliged User
USER 1001
